/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.incidenciastecnico;

import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alumno
 */
public class Tecnico extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Tecnico.class.getName());
    private static TicketInterface ticket;
    private static DefaultTableModel model;
    private static ArrayList<Ticket> lista;

    /**
     * Creates new form Tecnico
     */
    public Tecnico() {
        initComponents();
        model = (DefaultTableModel) tabla.getModel();
        hiloAdd h = new hiloAdd();
        h.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        rolLabel = new javax.swing.JLabel();
        Scroll = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        asignarBtn = new javax.swing.JButton();
        resolverBtn = new javax.swing.JButton();
        descripcionBtn = new javax.swing.JButton();
        actualizarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label1.setText("TÉCNICO:");

        nombreLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nombreLabel.setText("PACO");

        label2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label2.setText("ROL:");

        rolLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rolLabel.setText("TÉCNICO DE HARDWARE");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID INCIDENCIA", "CLIENTE", "PRIORIDAD", "ESTADO", "TÉCNICO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setShowGrid(true);
        Scroll.setViewportView(tabla);

        asignarBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        asignarBtn.setText("ASIGNAR");
        asignarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignarBtnActionPerformed(evt);
            }
        });

        resolverBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        resolverBtn.setText("RESOLVER");

        descripcionBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        descripcionBtn.setText("DESCRIPCIÓN");
        descripcionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descripcionBtnActionPerformed(evt);
            }
        });

        actualizarBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        actualizarBtn.setText("ACTUALIZAR");
        actualizarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label1)
                        .addGap(18, 18, 18)
                        .addComponent(nombreLabel)
                        .addGap(40, 40, 40)
                        .addComponent(label2)
                        .addGap(18, 18, 18)
                        .addComponent(rolLabel))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(asignarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(134, 134, 134)
                            .addComponent(resolverBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(descripcionBtn)
                            .addGap(115, 115, 115)
                            .addComponent(actualizarBtn))
                        .addComponent(Scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 912, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label1)
                    .addComponent(nombreLabel)
                    .addComponent(label2)
                    .addComponent(rolLabel))
                .addGap(18, 18, 18)
                .addComponent(Scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(asignarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resolverBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descripcionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actualizarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void asignarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignarBtnActionPerformed

    }//GEN-LAST:event_asignarBtnActionPerformed

    private void actualizarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarBtnActionPerformed
        try {
            // TODO add your handling code here:
            add();
        } catch (RemoteException ex) {
            System.getLogger(Tecnico.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_actualizarBtnActionPerformed

    private void descripcionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descripcionBtnActionPerformed
        // TODO add your handling code here:
        if (tabla.getSelectedRow() == -1) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Selecciona una fila porfaplis",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        } else {
            Ticket t = lista.get(tabla.getSelectedRow());
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    t.getDescripcion(),
                    "Descripción de Incidencia " + t.getId(),
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
            );
        }
    }//GEN-LAST:event_descripcionBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Tecnico().setVisible(true));
        try {
            Registry reg = LocateRegistry.getRegistry("localhost", 1099);
            ticket = (TicketInterface) reg.lookup("TicketService");

        } catch (NotBoundException | RemoteException e) {
        }
    }

    private void add() throws RemoteException {
        model.setRowCount(0);
        lista = ticket.RecibirTicket();
        for (Ticket t : lista) {
            model.addRow(t.toArray());
        }
    }

    private class hiloAdd extends Thread {

        @Override
        public void run() {
            while (true) {
                try {
                    add();
                    Thread.sleep(4000);
                } catch (RemoteException | InterruptedException ex) {
                    System.getLogger(Tecnico.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Scroll;
    private javax.swing.JButton actualizarBtn;
    private javax.swing.JButton asignarBtn;
    private javax.swing.JButton descripcionBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JButton resolverBtn;
    private javax.swing.JLabel rolLabel;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
